package uz.depos.app.service.dto;

import uz.depos.app.domain.User;

/**
 * A DTO representing a user login, with generated by INN.
 */
public class LoginDTO {

    private String login;

    public LoginDTO() {
        // Empty constructor needed for Jackson.
    }

    public LoginDTO(String login) {
        this.login = login;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Override
    public String toString() {
        return "LoginDTO{" + "login='" + login + '\'' + '}';
    }
}
