package uz.depos.app.web.eds.yt_pkcs7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21
 * Generated source version: 2.2
 *
 */
@WebService(name = "Pkcs7", targetNamespace = "http://v1.pkcs7.plugin.ss.capi.yt.uz/")
@XmlSeeAlso({ ObjectFactory.class })
public interface Pkcs7 {
    /**
     *
     * @param document
     * @param apikey
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(
        localName = "createPkcs7",
        targetNamespace = "http://v1.pkcs7.plugin.ss.capi.yt.uz/",
        className = "z.eimzo.yt_pkcs7.CreatePkcs7"
    )
    @ResponseWrapper(
        localName = "createPkcs7Response",
        targetNamespace = "http://v1.pkcs7.plugin.ss.capi.yt.uz/",
        className = "z.eimzo.yt_pkcs7.CreatePkcs7Response"
    )
    @Action(
        input = "http://v1.pkcs7.plugin.ss.capi.yt.uz/Pkcs7/createPkcs7Request",
        output = "http://v1.pkcs7.plugin.ss.capi.yt.uz/Pkcs7/createPkcs7Response"
    )
    String createPkcs7(
        @WebParam(name = "document", targetNamespace = "") byte[] document,
        @WebParam(name = "apikey", targetNamespace = "") String apikey
    );

    /**
     *
     * @param pkcs7B64
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(
        localName = "verifyPkcs7",
        targetNamespace = "http://v1.pkcs7.plugin.ss.capi.yt.uz/",
        className = "z.eimzo.yt_pkcs7.VerifyPkcs7"
    )
    @ResponseWrapper(
        localName = "verifyPkcs7Response",
        targetNamespace = "http://v1.pkcs7.plugin.ss.capi.yt.uz/",
        className = "z.eimzo.yt_pkcs7.VerifyPkcs7Response"
    )
    @Action(
        input = "http://v1.pkcs7.plugin.ss.capi.yt.uz/Pkcs7/verifyPkcs7Request",
        output = "http://v1.pkcs7.plugin.ss.capi.yt.uz/Pkcs7/verifyPkcs7Response"
    )
    String verifyPkcs7(@WebParam(name = "pkcs7B64", targetNamespace = "") String pkcs7B64);
}
