package uz.depos.app.web.eds.yt_pkcs7;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21
 * Generated source version: 2.2
 *
 */
@WebServiceClient(
    name = "Pkcs7Service",
    targetNamespace = "http://v1.pkcs7.plugin.ss.capi.yt.uz/",
    wsdlLocation = "http://127.0.0.1:9090/ytcapiss/pkcs7/v1?wsdl"
)
public class Pkcs7Service extends Service {

    private static final URL PKCS7SERVICE_WSDL_LOCATION;
    private static final WebServiceException PKCS7SERVICE_EXCEPTION;
    private static final QName PKCS7SERVICE_QNAME = new QName("http://v1.pkcs7.plugin.ss.capi.yt.uz/", "Pkcs7Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9090/ytcapiss/pkcs7/v1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PKCS7SERVICE_WSDL_LOCATION = url;
        PKCS7SERVICE_EXCEPTION = e;
    }

    public Pkcs7Service() {
        super(__getWsdlLocation(), PKCS7SERVICE_QNAME);
    }

    public Pkcs7Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PKCS7SERVICE_QNAME, features);
    }

    public Pkcs7Service(URL wsdlLocation) {
        super(wsdlLocation, PKCS7SERVICE_QNAME);
    }

    public Pkcs7Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PKCS7SERVICE_QNAME, features);
    }

    public Pkcs7Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Pkcs7Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Pkcs7
     */
    @WebEndpoint(name = "Pkcs7Port")
    public Pkcs7 getPkcs7Port() {
        return super.getPort(new QName("http://v1.pkcs7.plugin.ss.capi.yt.uz/", "Pkcs7Port"), Pkcs7.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Pkcs7
     */
    @WebEndpoint(name = "Pkcs7Port")
    public Pkcs7 getPkcs7Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://v1.pkcs7.plugin.ss.capi.yt.uz/", "Pkcs7Port"), Pkcs7.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PKCS7SERVICE_EXCEPTION != null) {
            throw PKCS7SERVICE_EXCEPTION;
        }
        return PKCS7SERVICE_WSDL_LOCATION;
    }
}
